PARAMETERS = {
    "date": "Дата",
    "time": "Время",
    "chd_spontan": "ЧД спонтан",
    "ofv1": "ОФВ1",
    "fzhel": "ФЖЕЛ",
    "foe": "ФОЕ",
    "oel": "ОЕЛ",
    "ool": "ООЛ",
    "ofv1_fzhel": "ОФВ1/ФЖЕЛ",
    "pos": "ПОС",
    "mos25": "МОС25",
    "mos50": "МОС50",
    "mos75": "МОС75",
    "sos25_75": "СОС 25-75",
    "chss": "ЧСС",
    "chss_min": "ЧСС мин",
    "chss_max": "ЧСС макс",
    "adsis": "АДсис",
    "adsis_min": "Адсис мин",
    "adsis_max": "Адсис макс",
    "addias": "АДдиас",
    "addias_min": "Аддиас мин",
    "addias_max": "Аддиас макс",
    "adsr": "АДср",
    "adsr_min": "Адср мин",
    "adsr_max": "Адср макс",
    "spo2": "SpO2",
    "diurez_ml_h": "Диурез мл/ч",
    "gemoglobin": "Гемоглобин",
    "neytrofily": "Нейтрофилы",
    "limfocity": "Лимфоциты",
    "gematokrit": "Гематокрит",
    "leykocity": "Лейкоциты",
    "pya": "п/я",
    "albumin": "Альбумин",
    "kreatinin": "Креатинин",
    "skf": "СКФ",
    "nlr": "NLR",
    "glyukoza_krovi": "Глюкоза крови",
    "uo": "УО",
    "si": "СИ",
    "iopss": "ИОПСС",
    "sao": "СаО",
    "do2": "DO2",
    "vbd": "ВБД",
    "fio2": "FiO2",
    "etco2": "EtCO2",
    "vt": "VT",
    "f": "f",
    "mv": "MV",
    "peep": "PEEP",
    "ppik": "Pпик",
    "rplato": "Рплато",
    "delta_p": "ΔP",
    "cstat": "Сstat",
    "cdyn": "Cdyn",
    "ball_uzl": "Балл УЗЛ",
    "mas": "МАС",
    "qcon": "qCon",
    "qnox": "qNOX",
    "emg": "EMG",
    "pn_arter": "Pн артер.",
    "be_arter": "BE артер.",
    "hco3_arter": "HCO3 артер.",
    "laktat_arter": "Лактат артер.",
    "rao2": "РаО2",
    "rao2_fio2": "РаО2/FiO2",
    "raso2": "РаСО2",
    "sao2": "SаO2",
    "rin_prick": "Рin-prick",
    "cold_test": "Cold-test",
    "motorny_blok": "Моторный блок",
    "t_operacii": "t операции",
    "t_probuzhdeniya": "t пробуждения",
    "t_do_extubacii": "t до экстубации",
    "obem_infuzia": "Объем инфузии",
    "polo": "ПОЛО",
    "frenikus_sind": "Френикус синд.",
    "frenikus_crsh": "Френикус/ ЦРШ",
    "opp": "ОПП",
    "oslozhneniya": "Осложнения",
    "bol_crsh": "Боль/ ЦРШ",
    "bol_crsh_min": "Боль/ ЦРШ Мин",
    "bol_crsh_max": "Боль/ ЦРШ Макс",
    "toshnota_rvota": "Тошнота/рвота",
    "shkala_aldrete": "Шкала Aldrete",
    "vremya_dost_aldrete": "Время достижения Aldrete 9-10 б.",
    "t_aktivizacii": "t активизации",
    "t_voss_peristalt": "t восс. перистал.",
    "t_othozhd_gazov": "t отхожд. газов",
    "rashod_opiatov": "Расход опиатов",
    "bol_mochev_cat": "Боль мочев кат",
    "t_v_aro1": "t в АРО (1)",
    "t_intensiv_boli": "t интенсив. боли",
    "t_voss_foe": "t восс. ФОЕ",
    "t_voss_skf": "t восс. СКФ",
    "t_v_aro2": "t в АРО (2)",
    "qor15": "QoR-15",
    "udovletvoren": "Удовлетворен.",
}

PARAMETER_KEYS = list(PARAMETERS.keys())
